### Create an order
POST {{baseUrl}}/orders
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "requisitionId": "{{kitCode}}",
    "integrationId": "{{integrationId}}",
    "patient": {
        "name": "Miso",
        "sex": "{{referenceData.sex.male}}",
        "species": "{{referenceData.species.dog}}",
        "breed": "{{referenceData.breed.jack-russell-terrier}}",
        "birthdate": "2023-03-05"
    },
    "client": {
        "firstName": "Gonzalo",
        "lastName": "Bellver",
        "contact": {
            "email": "gonzalo@linehq.com",
            "phone": "1234567890"
        }
    },
    "veterinarian": {
        "firstName": "Foo",
        "lastName": "Bar",
        "identifier": [
			{
				"system": "pims:veterinarian:id",
				"value": "9999"
			}
		]
    },
    "testCodes": [
		{ "code": "foo"}
	],
    "labRequisitionInfo": {
        "KitCode": "{{kitCode}}"
    }
}

> {%
  client.test("Order was created successfully", function () {
    client.assert(response.status === 201, "Order creation failed");
  });
%}
